1. 'values added: 20'
2. 'final result: 20'
   
3. 'values added: 20'
4. The code returns an error because the variable result is only accessible in the block it was declared in. The variable was result was called outside this block therefore causing an error.

5. Line 9 is never reached and doesn't print anything because line 7 threw an error. The code threw an error because we can't reassign a const variable.

6. Again, the code returns an error because the variable result is only accessible in the block it was declared in. The variable was result was called outside this block therefore causing an error.

